### ISSUE TITLE
Remove binary releases.

### ISSUE THREAD

**Issue by ryancdotorg** [XopMC/brainflayer-Windows#2]
Hello,

Distributing binary releases of brainflayer or derived software is not permitted by copyright. Please remove the binary release - if you do not do so I will file a DMCA report with GitHub to have it removed.

Brainflayer is "all rights reserved", however as an *exception* as required by GitHub's terms of service, the repository may be *forked* and modifications posted. To be clear, it is also not permitted to otherwise share the source code anywhere, including GitHub.

**Comment by XopMC** [comment]
> Hello,
> 
> Distributing binary releases of brainflayer or derived software is not permitted by copyright. Please remove the binary release - if you do not do so I will file a DMCA report with GitHub to have it removed.
> 
> Brainflayer is "all rights reserved", however as an _exception_ as required by GitHub's terms of service, the repository may be _forked_ and modifications posted. To be clear, it is also not permitted to otherwise share the source code anywhere, including GitHub.

Done, all executable files have been deleted

**Comment by ryancdotorg** [comment]
Thank you, I appreciate your understanding. Hopefully my stern language wasn't too off-putting.

My reasoning behind this is that ready to run brainflayer binaries/executable are an extremely attractive platform for bundled malware (or simply being malware). I've noticed this happening several times, and this copyright policy allows me to have such things removed.

**Comment by XopMC** [comment]
> 

No problem, I get it 🤗

I'll just do the instructions to compile the program

**Comment by CookLand** [comment]
> Hello,
> 
> Distributing binary releases of brainflayer or derived software is not permitted by copyright. Please remove the binary release - if you do not do so I will file a DMCA report with GitHub to have it removed.
> 
> Brainflayer is "all rights reserved", however as an _exception_ as required by GitHub's terms of service, the repository may be _forked_ and modifications posted. To be clear, it is also not permitted to otherwise share the source code anywhere, including GitHub.

hello. make a similar option in your repository in order to be able to run on the windows platform. you haven't had updates for a long time. thank you in advance if you do this .

**Comment by ryancdotorg** [comment]
It runs fine under WSL2 if you don't want to use a full Linux install. 🤷
